### ISSUE TITLE
How to bind to 0.0.0.0??

### ISSUE THREAD

**Issue by tony1016** [johanhaleby/docker-machine-port-forwarder#1]
Great job.But I find that it's bind to 127.0.0.1 which can't be connected outside macOS.How can I make it bind to 0.0.0.0??

**Comment by johanhaleby** [comment]
@tony1016 Somehow I've missed this, sorry! Never the less I don't think `pf` should support this. I assume that most people don't want to expose the port to the outside world. In this case I think you should just use the `docker-machine` command (or perhaps you could use ngrok if that's easier to remember).
